//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemlik_Kitabevim
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_KITAPLAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_KITAPLAR()
        {
            this.TBL_KAYITLAR = new HashSet<TBL_KAYITLAR>();
        }
    
        public int KITAPID { get; set; }
        public string KITAPAD { get; set; }
        public string KONUSU { get; set; }
        public string YAZARI { get; set; }
        public string SAYFASI { get; set; }
        public string YAYINEVI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_KAYITLAR> TBL_KAYITLAR { get; set; }
    }
}
