//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemlik_Kitabevim
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_OGRENCILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_OGRENCILER()
        {
            this.TBL_KAYITLAR = new HashSet<TBL_KAYITLAR>();
        }
    
        public int ID { get; set; }
        public string ADSOYAD { get; set; }
        public string DOGUMTARIHI { get; set; }
        public string TELEFON { get; set; }
        public string MAIL { get; set; }
        public string UYELIKTARIHI { get; set; }
        public string CINSIYET { get; set; }
        public string TCNO { get; set; }
        public string ADRES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_KAYITLAR> TBL_KAYITLAR { get; set; }
    }
}
