//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemlik_Kitabevim
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_KAYITLAR
    {
        public int KAYITID { get; set; }
        public Nullable<int> KULLANICI { get; set; }
        public Nullable<int> KITAPID { get; set; }
        public Nullable<System.DateTime> ALISTARIH { get; set; }
        public Nullable<System.DateTime> SONTARIH { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        public virtual TBL_KITAPLAR TBL_KITAPLAR { get; set; }
        public virtual TBL_OGRENCILER TBL_OGRENCILER { get; set; }
    }
}
